n1 = int(input())
n2 = int(input())
n3 = int(input())
n4 = int(input())
n5 = int(input())
n6 = int(input())
n7 = int(input())
n8 = int(input())
n9 = int(input())
n10 = int(input())

print(n1, n2, n3, n4)
print(n5, n6, n7, n8)
print(n9, n10)

